#!/usr/bin/env python3

"""
The raw Neuron accelerometer is used instead of the unsigned "bend_deg"column.  
With Neuron 4's measured mounting, the absolute total bend angle is atan2(-acc_x, acc_z).  Negative angles mean that thrust has reached/passed the straight-arm stop and are clamped to zero.  The URDF's summed joint limit is approximately 170 degrees, which is used as the upper clamp.

Four monotonic surfaces are fitted for pressure up/down and PWM up/down.  PWM is converted to thrust with the calibration already used by Hugmy:

  pwm = -0.000679 * thrust^2 + 0.044878 * thrust + 0.5

This is an offline generator; pandas and scikit-learn are not runtime package dependencies of Hugmy.
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor


PRESSURE_GRID = np.arange(0.0, 50.0 + 1.0e-9, 5.0)
THRUST_GRID = np.arange(0.0, 9.0 + 1.0e-9, 0.5)
DIRECTIONS = ("down", "up")
PWM_QUADRATIC = -0.000679
PWM_LINEAR = 0.044878
PWM_IDLE = 0.5
MAX_BEND_DEG = 170.0


def pwm_to_thrust(pwm):
    discriminant = PWM_LINEAR ** 2 - 4.0 * PWM_QUADRATIC * (PWM_IDLE - pwm)
    if np.any(discriminant < 0.0):
        raise ValueError("PWM is outside the calibrated thrust conversion")
    return (-PWM_LINEAR + np.sqrt(discriminant)) / (2.0 * PWM_QUADRATIC)


def load_conditions(path):
    raw = pd.read_csv(path)
    required = {
        "condition_id", "repeat", "pressure_direction", "pwm_direction",
        "pressure_kpa", "motor_pwm", "acc_x", "acc_z",
    }
    missing = required.difference(raw.columns)
    if missing:
        raise ValueError("{} is missing columns: {}".format(path, sorted(missing)))

    conditions = raw.groupby("condition_id", sort=True).agg(
        repeat=("repeat", "first"),
        pressure_direction=("pressure_direction", "first"),
        thrust_direction=("pwm_direction", "first"),
        pressure_kpa=("pressure_kpa", "mean"),
        motor_pwm=("motor_pwm", "first"),
        acc_x=("acc_x", "mean"),
        acc_z=("acc_z", "mean"),
        sample_count=("condition_id", "size"),
    ).reset_index()

    angle = np.degrees(np.arctan2(-conditions.acc_x, conditions.acc_z))
    angle = np.where(angle < 0.0, angle + 360.0, angle)
    angle = np.where(angle > 180.0, angle - 360.0, angle)
    conditions["angle_deg"] = np.clip(angle, 0.0, MAX_BEND_DEG)
    conditions["thrust_n"] = pwm_to_thrust(conditions.motor_pwm.to_numpy())
    conditions["source"] = Path(path).name
    return conditions


def fit_tables(conditions):
    query = np.array([[pressure, thrust]
                      for pressure in PRESSURE_GRID for thrust in THRUST_GRID])
    tables = np.empty((2, 2, len(PRESSURE_GRID), len(THRUST_GRID)))
    for pressure_index, pressure_direction in enumerate(DIRECTIONS):
        for thrust_index, thrust_direction in enumerate(DIRECTIONS):
            branch = conditions[
                (conditions.pressure_direction == pressure_direction) &
                (conditions.thrust_direction == thrust_direction)]
            if len(branch) < 20:
                raise ValueError("too few samples for branch {}/{}: {}".format(
                    pressure_direction, thrust_direction, len(branch)))
            model = HistGradientBoostingRegressor(
                max_iter=300,
                max_leaf_nodes=20,
                min_samples_leaf=5,
                l2_regularization=2.0,
                monotonic_cst=[1, -1],
                random_state=1,
            )
            model.fit(branch[["pressure_kpa", "thrust_n"]].to_numpy(),
                      branch.angle_deg.to_numpy())
            tables[pressure_index, thrust_index] = np.clip(
                model.predict(query).reshape(len(PRESSURE_GRID), len(THRUST_GRID)),
                0.0, MAX_BEND_DEG)
    return tables


def array_values(values):
    return ", ".join("{:.6f}".format(value) for value in values)


def render_header(tables, sources):
    lines = [
        "#ifndef HUGMY_PRESSURE_THRUST_BEND_MODEL_DATA_H",
        "#define HUGMY_PRESSURE_THRUST_BEND_MODEL_DATA_H",
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        "// Generated by fit_pressure_thrust_bend_model.py from:",
    ]
    lines.extend("//   {}".format(Path(source).name) for source in sources)
    lines.extend([
        "// Absolute bend is reconstructed from Neuron 4's mean acceleration.",
        "// Tables are monotonic: pressure increases bend; thrust decreases it.",
        "namespace hugmy { namespace bend_model_data {",
        "constexpr size_t PRESSURE_COUNT = {};".format(len(PRESSURE_GRID)),
        "constexpr size_t THRUST_COUNT = {};".format(len(THRUST_GRID)),
        "using ThrustRow = std::array<double, THRUST_COUNT>;",
        "using PressureTable = std::array<ThrustRow, PRESSURE_COUNT>;",
        "using ThrustDirectionTables = std::array<PressureTable, 2>;",
        "using DirectionTables = std::array<ThrustDirectionTables, 2>;",
        "constexpr std::array<double, PRESSURE_COUNT> pressure_grid{{{{ {} }}}};".format(
            array_values(PRESSURE_GRID)),
        "constexpr std::array<double, THRUST_COUNT> thrust_grid{{{{ {} }}}};".format(
            array_values(THRUST_GRID)),
        "// Index order: [pressure down/up][thrust down/up][pressure][thrust].",
        "constexpr DirectionTables angle_grid_deg{{",
    ])
    for pressure_direction in range(2):
        lines.append("  ThrustDirectionTables{{")
        for thrust_direction in range(2):
            lines.append("    PressureTable{{")
            for row in tables[pressure_direction, thrust_direction]:
                lines.append("      ThrustRow{{{{ {} }}}},".format(array_values(row)))
            lines.append("    }},")
        lines.append("  }},")
    lines.extend([
        "}};",
        "}}  // namespace hugmy::bend_model_data",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("raw_csv", nargs="+", help="identification raw CSV files")
    parser.add_argument("--output", required=True, help="generated C++ data header")
    args = parser.parse_args()

    conditions = pd.concat([load_conditions(path) for path in args.raw_csv],
                           ignore_index=True)
    tables = fit_tables(conditions)
    Path(args.output).write_text(render_header(tables, args.raw_csv))
    print("wrote {} from {} conditions".format(args.output, len(conditions)))
    print("angle range: {:.3f} .. {:.3f} deg".format(
        tables.min(), tables.max()))


if __name__ == "__main__":
    main()
